name: Gradle Dist

on: [push, repository_dispatch]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 7
      uses: actions/setup-java@v2
      with:
        java-version: '7'
        distribution: 'adopt'
        server-id: github # Value of the distributionManagement/repository/id field of the pom.xml
        settings-path: ${{ github.workspace }} # location for the settings.xml file

    - name: Build with Gradle
      run: gradle distZip
    - name: unzip dist
      run: |
        unzip build/distributions/nand2tetris-1.0-SNAPSHOT.zip
        chmod +x nand2tetris-1.0-SNAPSHOT/bin/visualizer/visualizer*
    - uses: actions/upload-artifact@v2
      with:
        name: nand2tetris
        path: nand2tetris-1.0-SNAPSHOT
    - name: Zip :)
      run: |
        chmod +x nand2tetris-1.0-SNAPSHOT/*.sh
        zip -r nand2tetris.zip nand2tetris-1.0-SNAPSHOT/*
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: nand2tetris.zip
